### ISSUE TITLE
kan_bu_dong

### ISSUE THREAD

**Issue by Yubei-1** [610yilingliu/missevan_download#4]
Traceback (most recent call last):
  File "C:\Users\yu\Desktop\missevan_download-master\downloader.py", line 67, in <module>
    dl_mp3(id)
  File "C:\Users\yu\Desktop\missevan_download-master\downloader.py", line 26, in dl_mp3
    sound_url = re.findall(r"soundurl\":\"(.*?)\"", json_content)[0]
IndexError: list index out of range

**Comment by zhendery** [comment]
付费剧需要填自己的cookie，否则会找不到soundurl报错
